import { FileText, Download, Calendar, Building2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface Report {
  id: string;
  name: string;
  dateFrom: string;
  dateTo: string;
  createdAt: string;
  recordCount: number;
  totalCO2: number;
  totalCH4: number;
  totalN2O: number;
  status: "complete" | "draft";
}

const mockReports: Report[] = [
  {
    id: "1",
    name: "Inventario anual de GyGei 2024",
    dateFrom: "2024-01-01",
    dateTo: "2024-12-31",
    createdAt: "2024-12-15",
    recordCount: 1247,
    totalCO2: 24156,
    totalCH4: 487,
    totalN2O: 66,
    status: "complete",
  },
  {
    id: "2",
    name: "Q4 2024 Reporte de Emisiones",
    dateFrom: "2024-10-01",
    dateTo: "2024-12-31",
    createdAt: "2025-01-02",
    recordCount: 312,
    totalCO2: 5842,
    totalCH4: 118,
    totalN2O: 16,
    status: "complete",
  },
  {
    id: "3",
    name: "Q1 2025 Reporte de Emisiones",
    dateFrom: "2025-01-01",
    dateTo: "2025-03-31",
    createdAt: "2025-01-28",
    recordCount: 89,
    totalCO2: 1956,
    totalCH4: 42,
    totalN2O: 5,
    status: "draft",
  },
];

const Reports = () => {
  const { toast } = useToast();

  const generatePDF = (report: Report) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(45, 80, 75);
    doc.text("EmissionTrack", 20, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Reporte de GyGEI", 20, 28);

    // Organization Info
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(report.name, 20, 45);
    
    doc.setFontSize(10);
    doc.setTextColor(80);
    doc.text(`Organización: Telcel`, 20, 55);
    doc.text(`ID Organización: ORG-2024-001`, 20, 62);
    doc.text(`Industria: Manufactura`, 20, 69);
    doc.text(`Periodo reportado: ${report.dateFrom} to ${report.dateTo}`, 20, 76);
    doc.text(`Generado: ${new Date().toLocaleDateString()}`, 20, 83);

    // Summary Box
    doc.setDrawColor(200);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(20, 92, 170, 35, 3, 3, "FD");
    
    doc.setFontSize(11);
    doc.setTextColor(45, 80, 75);
    doc.text("Emissions Summary", 25, 102);
    
    doc.setFontSize(10);
    doc.setTextColor(60);
    doc.text(`Total CO₂: ${report.totalCO2.toLocaleString()} tonnes`, 25, 112);
    doc.text(`Total CH₄: ${report.totalCH4.toLocaleString()} kg`, 90, 112);
    doc.text(`Total N₂O: ${report.totalN2O.toLocaleString()} kg`, 145, 112);
    doc.text(`Records: ${report.recordCount.toLocaleString()}`, 25, 122);

    // Sample emissions table
    autoTable(doc, {
      startY: 135,
      head: [["Sector", "Actividad", "Tipo de combustible", "Volumen", "Unidad", "CO₂ (t)", "CH₄ (kg)", "N₂O (kg)"]],
      body: [
        ["Transporte", "Operaciones de flotilla", "Disel", "15,000", "L", "40.20", "1.80", "0.30"],
        ["Manufactura", "Linea de producción A", "Gas ", "8,500", "m³", "16.07", "0.09", "0.09"],
        ["Construcción", "Calefacción", "Gas Natura", "12,300", "m³", "23.25", "0.12", "0.12"],
        ["Transporte", "Vehiculos de entrega", "Gasolina", "9,200", "L", "21.25", "0.92", "0.18"],
        ["Construcción", "Electricidad de oficina", "Electriciidad", "45,000", "kWh", "18.90", "0.45", "0.23"],
      ],
      styles: { fontSize: 9 },
      headStyles: { fillColor: [45, 95, 85] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Page ${i} of ${pageCount} | Generated by EmissionTrack`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: "center" }
      );
    }

    doc.save(`${report.name.replace(/\s+/g, "_")}.pdf`);
    
    toast({
      title: "PDF Generated",
      description: `${report.name} Ha sido descargado`,
    });
  };

  return (
    <div className="animate-fade-in">
      <div className="page-header flex items-center justify-between">
        <div>
          <h1 className="page-title">Reports</h1>
          <p className="page-description">
            Generar y exportar reporte de cumplimiento de emisiones
          </p>
        </div>
        <Button>
          <FileText className="h-4 w-4 mr-2" />
          New Report
        </Button>
      </div>

      {/* Reports List */}
      <div className="space-y-4">
        {mockReports.map((report) => (
          <div
            key={report.id}
            className="card-elevated p-6 flex items-center justify-between hover:shadow-md transition-shadow"
          >
            <div className="flex items-start gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <FileText className="h-6 w-6" />
              </div>
              <div>
                <div className="flex items-center gap-3 mb-1">
                  <h3 className="font-semibold">{report.name}</h3>
                  <Badge
                    variant={report.status === "complete" ? "default" : "secondary"}
                    className={report.status === "complete" ? "bg-success text-success-foreground" : ""}
                  >
                    {report.status === "complete" ? "Complete" : "Draft"}
                  </Badge>
                </div>
                <div className="flex items-center gap-4 text-sm text-muted-foreground">
                  <span className="flex items-center gap-1">
                    <Calendar className="h-4 w-4" />
                    {report.dateFrom} to {report.dateTo}
                  </span>
                  <span className="flex items-center gap-1">
                    <Building2 className="h-4 w-4" />
                    {report.recordCount.toLocaleString()} records
                  </span>
                </div>
                <div className="flex gap-6 mt-3 text-sm">
                  <span>
                    <strong className="text-chart-co2">{report.totalCO2.toLocaleString()}</strong>{" "}
                    <span className="text-muted-foreground">t CO₂</span>
                  </span>
                  <span>
                    <strong className="text-chart-ch4">{report.totalCH4.toLocaleString()}</strong>{" "}
                    <span className="text-muted-foreground">kg CH₄</span>
                  </span>
                  <span>
                    <strong className="text-chart-n2o">{report.totalN2O.toLocaleString()}</strong>{" "}
                    <span className="text-muted-foreground">kg N₂O</span>
                  </span>
                </div>
              </div>
            </div>

            <div className="flex gap-2">
              <Button variant="outline" onClick={() => generatePDF(report)}>
                <Download className="h-4 w-4 mr-2" />
                PDF
              </Button>
              <Button variant="outline">
                <FileText className="h-4 w-4 mr-2" />
                Excel
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Reports;
