import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import type { AtmosphericEmissionsData } from "@/types/atmosphericEmissions";

interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: { finalY: number };
}

export const exportAtmosphericToPDF = (data: AtmosphericEmissionsData, orgName: string = "Acme Corporation") => {
  const doc = new jsPDF() as jsPDFWithAutoTable;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(45, 80, 75);
  doc.text("EmissionTrack", 20, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Atmospheric Emissions Report - RENE Section II", 20, 28);

  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(`Organization: ${orgName}`, 20, 42);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 50);

  let startY = 60;

  // Fixed Sources
  doc.setFontSize(14);
  doc.setTextColor(45, 80, 75);
  doc.text("3.1 Fixed Sources", 20, startY);

  const fixedTotals = {
    co2: data.fixedSources.reduce((sum, r) => sum + r.co2Emissions, 0),
    ch4: data.fixedSources.reduce((sum, r) => sum + r.ch4Emissions, 0),
    n2o: data.fixedSources.reduce((sum, r) => sum + r.n2oEmissions, 0),
  };

  autoTable(doc, {
    startY: startY + 5,
    head: [["Equipment Type", "Fuel", "Annual Consumption", "Operating Hours", "Estimation Method", "CO₂", "CH₄", "N₂O"]],
    body: [
      ...data.fixedSources.map((r) => [
        r.equipmentType,
        r.fuel,
        r.annualConsumption.toLocaleString(),
        r.operatingHours.toLocaleString(),
        r.estimationMethod,
        r.co2Emissions.toFixed(2),
        r.ch4Emissions.toFixed(3),
        r.n2oEmissions.toFixed(3),
      ]),
      ["TOTAL", "", "", "", "", fixedTotals.co2.toFixed(2), fixedTotals.ch4.toFixed(3), fixedTotals.n2o.toFixed(3)],
    ],
    styles: { fontSize: 8 },
    headStyles: { fillColor: [45, 95, 85], textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    footStyles: { fillColor: [220, 230, 225], fontStyle: "bold" },
  });

  startY = (doc.lastAutoTable?.finalY ?? startY) + 50;

  // Mobile Sources
  doc.setFontSize(14);
  doc.setTextColor(45, 80, 75);
  doc.text("3.2 Mobile Sources", 20, startY);

  const mobileTotals = {
    ghg: data.mobileSources.reduce((sum, r) => sum + r.ghgEmissions, 0),
  };

  autoTable(doc, {
    startY: startY + 5,
    head: [["Vehicle Type", "Fuel", "Annual Consumption", "Calculation Method", "GHG Emissions"]],
    body: [
      ...data.mobileSources.map((r) => [
        r.vehicleType,
        r.fuel,
        r.annualConsumption.toLocaleString(),
        r.calculationMethod,
        r.ghgEmissions.toFixed(2),
      ]),
      ["TOTAL", "", "", "", mobileTotals.ghg.toFixed(2)],
    ],
    styles: { fontSize: 8 },
    headStyles: { fillColor: [45, 95, 85], textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  startY = (doc.lastAutoTable?.finalY ?? startY) + 50;

  // Check if we need a new page
  if (startY > 240) {
    doc.addPage();
    startY = 20;
  }

  // Fugitive Emissions
  doc.setFontSize(14);
  doc.setTextColor(45, 80, 75);
  doc.text("3.3 Fugitive Emissions", 20, startY);

  const fugitiveTotals = {
    quantity: data.fugitiveEmissions.reduce((sum, r) => sum + r.estimatedQuantity, 0),
  };

  autoTable(doc, {
    startY: startY + 5,
    head: [["Gas Type", "Source", "Estimated Quantity", "Methodology"]],
    body: [
      ...data.fugitiveEmissions.map((r) => [
        r.gasType,
        r.source,
        r.estimatedQuantity.toFixed(2),
        r.methodology,
      ]),
      ["TOTAL", "", fugitiveTotals.quantity.toFixed(2), ""],
    ],
    styles: { fontSize: 8 },
    headStyles: { fillColor: [45, 95, 85], textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} | Atmospheric Emissions Report - Generated by EmissionTrack`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  doc.save("Atmospheric_Emissions_Report.pdf");
};

export const exportAtmosphericToExcel = (data: AtmosphericEmissionsData) => {
  const workbook = XLSX.utils.book_new();

  // Fixed Sources Sheet
  const fixedData = data.fixedSources.map((r) => ({
    "Equipment Type": r.equipmentType,
    "Fuel": r.fuel,
    "Annual Consumption": r.annualConsumption,
    "Operating Hours": r.operatingHours,
    "Estimation Method": r.estimationMethod,
    "CO₂ Emissions": r.co2Emissions,
    "CH₄ Emissions": r.ch4Emissions,
    "N₂O Emissions": r.n2oEmissions,
  }));
  fixedData.push({
    "Equipment Type": "TOTAL",
    "Fuel": "",
    "Annual Consumption": data.fixedSources.reduce((sum, r) => sum + r.annualConsumption, 0),
    "Operating Hours": data.fixedSources.reduce((sum, r) => sum + r.operatingHours, 0),
    "Estimation Method": "",
    "CO₂ Emissions": data.fixedSources.reduce((sum, r) => sum + r.co2Emissions, 0),
    "CH₄ Emissions": data.fixedSources.reduce((sum, r) => sum + r.ch4Emissions, 0),
    "N₂O Emissions": data.fixedSources.reduce((sum, r) => sum + r.n2oEmissions, 0),
  });
  const fixedSheet = XLSX.utils.json_to_sheet(fixedData);
  XLSX.utils.book_append_sheet(workbook, fixedSheet, "Fixed Sources");

  // Mobile Sources Sheet
  const mobileData = data.mobileSources.map((r) => ({
    "Vehicle Type": r.vehicleType,
    "Fuel": r.fuel,
    "Annual Consumption": r.annualConsumption,
    "Calculation Method": r.calculationMethod,
    "GHG Emissions": r.ghgEmissions,
  }));
  mobileData.push({
    "Vehicle Type": "TOTAL",
    "Fuel": "",
    "Annual Consumption": data.mobileSources.reduce((sum, r) => sum + r.annualConsumption, 0),
    "Calculation Method": "",
    "GHG Emissions": data.mobileSources.reduce((sum, r) => sum + r.ghgEmissions, 0),
  });
  const mobileSheet = XLSX.utils.json_to_sheet(mobileData);
  XLSX.utils.book_append_sheet(workbook, mobileSheet, "Mobile Sources");

  // Fugitive Emissions Sheet
  const fugitiveData = data.fugitiveEmissions.map((r) => ({
    "Gas Type": r.gasType,
    "Source": r.source,
    "Estimated Quantity": r.estimatedQuantity,
    "Methodology": r.methodology,
  }));
  fugitiveData.push({
    "Gas Type": "TOTAL",
    "Source": "",
    "Estimated Quantity": data.fugitiveEmissions.reduce((sum, r) => sum + r.estimatedQuantity, 0),
    "Methodology": "",
  });
  const fugitiveSheet = XLSX.utils.json_to_sheet(fugitiveData);
  XLSX.utils.book_append_sheet(workbook, fugitiveSheet, "Fugitive Emissions");

  XLSX.writeFile(workbook, "Atmospheric_Emissions_Report.xlsx");
};

export const exportAtmosphericToWord = (data: AtmosphericEmissionsData, orgName: string = "Acme Corporation") => {
  // Create HTML content that can be opened as a Word document
  const fixedTotals = {
    co2: data.fixedSources.reduce((sum, r) => sum + r.co2Emissions, 0),
    ch4: data.fixedSources.reduce((sum, r) => sum + r.ch4Emissions, 0),
    n2o: data.fixedSources.reduce((sum, r) => sum + r.n2oEmissions, 0),
  };
  const mobileTotals = {
    ghg: data.mobileSources.reduce((sum, r) => sum + r.ghgEmissions, 0),
  };
  const fugitiveTotals = {
    quantity: data.fugitiveEmissions.reduce((sum, r) => sum + r.estimatedQuantity, 0),
  };

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Atmospheric Emissions Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #2d504b; }
        h2 { color: #2d5f55; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin: 15px 0; }
        th { background-color: #2d5f55; color: white; padding: 10px; text-align: left; border: 1px solid #ddd; }
        td { padding: 8px; border: 1px solid #ddd; }
        tr:nth-child(even) { background-color: #f8fafc; }
        .total-row { background-color: #dce6e1 !important; font-weight: bold; }
        .number { text-align: right; }
        .header { margin-bottom: 30px; }
        .meta { color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>EmissionTrack</h1>
        <p class="meta">Atmospheric Emissions Report - RENE Section II</p>
        <p><strong>Organization:</strong> ${orgName}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
      </div>

      <h2>3.1 Fixed Sources</h2>
      <table>
        <tr>
          <th>Equipment Type</th>
          <th>Fuel</th>
          <th>Annual Consumption</th>
          <th>Operating Hours</th>
          <th>Estimation Method</th>
          <th>CO₂ Emissions</th>
          <th>CH₄ Emissions</th>
          <th>N₂O Emissions</th>
        </tr>
        ${data.fixedSources.map((r) => `
          <tr>
            <td>${r.equipmentType}</td>
            <td>${r.fuel}</td>
            <td class="number">${r.annualConsumption.toLocaleString()}</td>
            <td class="number">${r.operatingHours.toLocaleString()}</td>
            <td>${r.estimationMethod}</td>
            <td class="number">${r.co2Emissions.toFixed(2)}</td>
            <td class="number">${r.ch4Emissions.toFixed(3)}</td>
            <td class="number">${r.n2oEmissions.toFixed(3)}</td>
          </tr>
        `).join("")}
        <tr class="total-row">
          <td>TOTAL</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="number">${fixedTotals.co2.toFixed(2)}</td>
          <td class="number">${fixedTotals.ch4.toFixed(3)}</td>
          <td class="number">${fixedTotals.n2o.toFixed(3)}</td>
        </tr>
      </table>

      <h2>3.2 Mobile Sources</h2>
      <table>
        <tr>
          <th>Vehicle Type</th>
          <th>Fuel</th>
          <th>Annual Consumption</th>
          <th>Calculation Method</th>
          <th>GHG Emissions</th>
        </tr>
        ${data.mobileSources.map((r) => `
          <tr>
            <td>${r.vehicleType}</td>
            <td>${r.fuel}</td>
            <td class="number">${r.annualConsumption.toLocaleString()}</td>
            <td>${r.calculationMethod}</td>
            <td class="number">${r.ghgEmissions.toFixed(2)}</td>
          </tr>
        `).join("")}
        <tr class="total-row">
          <td>TOTAL</td>
          <td></td>
          <td></td>
          <td></td>
          <td class="number">${mobileTotals.ghg.toFixed(2)}</td>
        </tr>
      </table>

      <h2>3.3 Fugitive Emissions</h2>
      <table>
        <tr>
          <th>Gas Type</th>
          <th>Source</th>
          <th>Estimated Quantity</th>
          <th>Methodology</th>
        </tr>
        ${data.fugitiveEmissions.map((r) => `
          <tr>
            <td>${r.gasType}</td>
            <td>${r.source}</td>
            <td class="number">${r.estimatedQuantity.toFixed(2)}</td>
            <td>${r.methodology}</td>
          </tr>
        `).join("")}
        <tr class="total-row">
          <td>TOTAL</td>
          <td></td>
          <td class="number">${fugitiveTotals.quantity.toFixed(2)}</td>
          <td></td>
        </tr>
      </table>
    </body>
    </html>
  `;

  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "Atmospheric_Emissions_Report.doc";
  link.click();
  URL.revokeObjectURL(url);
};
